### ISSUE TITLE
Incomplete Data Download Logic

### ISSUE THREAD

**Issue by dzorlu** [prakharguptaz/Instructdial#1]
Hello- Thank you for releasing the code and this most comprehensive dialogue dataset.

I may be missing something, but I noticed that some of the dataset downloads seem broken. Are you going to push an updated version of the code? 

For example, 

[dialoglue](https://github.com/prakharguptaz/Instructdial/blob/main/datasets/dialoglue.sh)  should work as following:

```
 git clone https://github.com/alexa/dialoglue.git
cd data_utils 
bash download_data.sh
cd ..
```

[dialogre](https://github.com/prakharguptaz/Instructdial/blob/main/datasets/dialogre.sh) shd work as following:

```
 git clone git@github.com:nlpdata/dialogre.git

mkdir ./datasets/dialogre
wget -P ./dialogre/data_v2/en/data https://raw.githubusercontent.com/nlpdata/dialogre/master/data_v2/en/data/dev.json
wget -P ./dialogre/data_v2/en/data https://raw.githubusercontent.com/nlpdata/dialogre/master/data_v2/en/data/test.json
wget -P ./dialogre/data_v2/en/data https://raw.githubusercontent.com/nlpdata/dialogre/master/data_v2/en/data/train.json
 rm -rf dialogre/.git
```

Getting the following error when `wow` dataset download logic is run

```
python: can't open file './wizard_generator.py': [Errno 2] No such file or directory
```

There may be more, these are the issues I have run into so far. I will be also happy to push the fixes.

Thank you
Deniz

**Comment by prakharguptaz** [comment]
Thanks for raising the issues. We are actively trying to fix them. We will push a fix in 2-3 days.

**Comment by dzorlu** [comment]
Hey- Just pushed a fix [here](https://github.com/prakharguptaz/Instructdial/pull/2). Please let me know if the PR works for you. Thanks for this awesome dataset again. 

Deniz

**Comment by exe1023** [comment]
Fixed the error related to WoW dataset in the commit https://github.com/prakharguptaz/Instructdial/commit/a429b361dd58964a7ccb1c3a9ceedcf304d60e36.
