### ISSUE TITLE
Task mixture for the hosted models

### ISSUE THREAD

**Issue by cuthalionn** [prakharguptaz/Instructdial#13]
Hi, thanks for sharing and maintaining this great code base!

I want to replicate the training of your main model hosted in [huggingface](https://huggingface.co/prakharz/DIAL-T0) but I am unsure which task mixture you used for the training. Could you share the list of tasks for both train and test?

Thanks!

**Comment by prakharguptaz** [comment]
Thanks for your interest. 
The config files for models we perform our main experiments on (Table 1 in the paper) are- [train ](https://github.com/prakharguptaz/Instructdial/blob/main/configs/experiments/leave_task_train.json) [test](https://github.com/prakharguptaz/Instructdial/blob/main/configs/experiments/leave_task_test.json)

The models released on huggingface are trained on all possible tasks and there are no test tasks per say. The config file is [alltasks-config](https://github.com/prakharguptaz/Instructdial/blob/main/configs/alltasksv1.json)
