### ISSUE TITLE
db-based-generation has the wrong identifier for context end

### ISSUE THREAD

**Issue by cuthalionn** [prakharguptaz/Instructdial#14]
Hi, 

Please correct me if I am wrong but I believe the context end identifier for db-based-generation task is wrong.
It should be:
`settings.EOD_SEP`
rather than
`settings.EOT_SEP`

https://github.com/prakharguptaz/Instructdial/blob/046de5c9a70d8791b6db8514f23fbfc50a3174c2/instruction_files/db_based_generation.py#L109

**Comment by prakharguptaz** [comment]
Thanks for pointing this out. Fixed
