### ISSUE TITLE
Replicating Table 2

### ISSUE THREAD

**Issue by cuthalionn** [prakharguptaz/Instructdial#17]
Thanks for managing the codebase actively again! 

Are the scripts for replicating Table 2 results provided? If so what are the detailed steps to replicate?

Thanks!

**Comment by prakharguptaz** [comment]
The steps are - create train and test data for the eval models by creating appropriate configs. Then use this [script ](https://github.com/prakharguptaz/Instructdial/blob/main/scripts/run_prob_generate.py) for model probability prediction. Then you can use the eval script for evaluation.

**Comment by cuthalionn** [comment]
I see, and are the configs for Table 2 available?
I am guessing these are the ones -> `t2t_eval_test3.json` and `t2t_eval_train3.json`, right ?

**Comment by prakharguptaz** [comment]
The train config is correct. the test config only has the eval-binary task. In case you want the testfile, I have uploaded it [here](https://drive.google.com/file/d/1a_7rGGi6dCsyShen8w6yLWkbPMSKWxka/view?usp=share_link)

**Comment by cuthalionn** [comment]
Thanks!
