### ISSUE TITLE
Task Mixing Counts

### ISSUE THREAD

**Issue by cuthalionn** [prakharguptaz/Instructdial#18]
Hello,

Section 4.2 of the paper indicates that the data point amount per task is set to 5K. However for some experiments the default configuration is set to 3K in the repository. I was wondering which one to follow (3K or 5K) to replicate the following models respectively:

1. T0 -> Publicly available huggingface model.
2. T0 -> Experimentation model (following Table 1 config)

Thank you!

**Comment by prakharguptaz** [comment]
Hi,

The settings in the repo are just for reference. We used 5k in the experiments and training for both models. In case you are constraint by compute, I don't expect much difference in performance between 3k and 5k settings.
