### ISSUE TITLE
Inquiry for task configurations

### ISSUE THREAD

**Issue by sdeva14** [prakharguptaz/Instructdial#19]
Hi, I first appreciate for an amazing work and sharing this!

I am following your guide, then I struck at the stage of "Creating seq2seq files from task files".

The problem is missing configurations for each task, but in the GitHub, I only can see "question_generation.json" under the 
"tasks_files-full-trainconfig1". Then I cannot generate other tasks due to missing configurations.

Could you guide me how to get other configurations or share others? 

Best,
Sungho

**Comment by prakharguptaz** [comment]
Hi,

You need to create the task files for all needed tasks first locally using instructions from "Creating task files for multiple tasks" and "Task files" sections of readme. Once that is done, you can create seq2seq files for train/test using configs (examples in https://github.com/prakharguptaz/Instructdial/tree/main/configs/experiments)

**Comment by sdeva14** [comment]
Oh Thanks a lot for the prompt response! It turns out that there was an error due to missing libraries.

I move on the next stage, but I stuck again.

How can I make a "valid.json" for model training? There is a description for train and test set, but I cannot find one for a valid set. 

Could you guide me how did you deal with it? or you didn't use it? Thanks!

**Comment by prakharguptaz** [comment]
glad it worked out. For validation file, we simply divide the train file onto 9:1 ratio using head and tail linux command
