### ISSUE TITLE
Missing wizard_generator.py file

### ISSUE THREAD

**Issue by alon-albalak** [prakharguptaz/Instructdial#8]
Hi, thank you so much for the effort you are putting into this repo!

The Instructdial/datasets/wow.sh script runs a python file called wizard_generator.py, but there isn't such a file in this project. Is it possible that wizard_generator.py simply hasn't been committed to the repo? Or do we need to download the script from another project?

**Comment by Xiao9905** [comment]
@prakharguptaz Hi,

I got the same error when processing the data. Could you help fix the problem? Many thanks!

**Comment by prakharguptaz** [comment]
Sorry missed this issue. The file we used is from https://github.com/nlpxucan/ZRKGC/blob/master/ZRKGC/preprocess/wizard_generator.py
I pushed a commit with the file
